<fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */?>">
    <div class="field customer_avatar">
        <label for="customer_avatar" class="label"><span><?php /* @escapeNotVerified */
                echo __('Upload Document') ?> (Allowed file extensions: .doc, .docx, .pdf, .jpg, .png.)</span></label>
        <div class="control">
            <input type="file" name="customer_avatar" id="customer_avatar" title="<?php /* @escapeNotVerified */
            echo __('Upload Document') ?>">
        </div>
    </div>
</fieldset>